//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllCustomers
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int ZipCode { get; set; }
        public byte InsuranceVerified { get; set; }
        public System.DateTime InsuranceExpirationDate { get; set; }
        public string Insurance_Co_ { get; set; }
        public int Insurance_Co___ { get; set; }
        public int InsuranceCompany { get; set; }
        public string Insurance_Co__State { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int id { get; set; }
    }
}
